# Configuration Options
title: TinyODOM-EX
author: "Joseph Zales"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true

header-pages:
  - documentation.html
  - resources.html


# Github Pages settings that cannot be changed
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
