# Configuration Options
title: TinyODOM-EX
author: "Joseph Zales"
theme: minima


# Github Pages settings that cannot be changed
lsi: false
safe: true
source: ECM202A_2025FALL_PROJECT_1
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
